[versions]
assertj = "3.26.3"
awsSdk = "2.26.3"
json = "20240303"
junit-jupiter = "5.11.3"
log4j2 = "2.24.3"
lombok = "1.18.36"
resilience4j = "2.2.0"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
aws-sdk-dynamodb = { module = "software.amazon.awssdk:dynamodb", version.ref = "awsSdk" }
json = { module = "org.json:json", version.ref = "json" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
log4j2-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j2" }
log4j2-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j2" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
resilience4j-retry = { module = "io.github.resilience4j:resilience4j-retry", version.ref = "resilience4j" }

[bundles]
logging = ["log4j2-core", "log4j2-slf4j-impl"]

[plugins]
